--- #YAML:1.0
name:                Net-Google-Calendar
version:             0.95
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    DateTime:                      0
    LWP::UserAgent:                0
    Net::Google::AuthSub:          0
    Test::More:                    0
    URI:                           0
    URI::Escape:                   0
    XML::Atom:                     0.23
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
